# The following redirect is intended for use with most SPAs that handle
# routing internally.
[[redirects]]
  from = "https://bio.torre.co"
  to = "/*"
  status = 200
  force = true

[[headers]]
  # Define which paths this specific [[headers]] block will cover.
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "https://bio.torre.co"